version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "3002:3000"
    depends_on:
      - user-service
