version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    networks:
      - clinic-network
    volumes:
      - ./user-service/logs:/app/logs

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "3002:3000"
    depends_on:
      - user-service
      - mongodb-booking
    networks:
      - clinic-network
    environment:
      - MONGO_URI=mongodb://mongodb-booking:27017/bookingdb
    volumes:
      - ./booking-service/logs:/app/logs

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3003:3000"
    networks:
      - clinic-network
    volumes:
      - ./product-service/logs:/app/logs

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    networks:
      - clinic-network
    volumes:
      - ./notification-service/logs:/app/logs

  mongodb-booking:
    image: mongo:6.0
    container_name: mongodb-booking
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_booking_data:/data/db
    networks:
      - clinic-network

networks:
  clinic-network:

volumes:
  mongodb_booking_data: