version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "3002:3000"
    depends_on:
      - user-service

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3003:3000"

  notification-service:
    build: ./notification-service
    ports:
      - "3004:3004"
    networks:
      - clinic-network

networks:
  clinic-network: