version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3001:3000"
    networks:
      - clinic-network
    volumes:
    - ./user-service/logs:/app/logs

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "3002:3000"
    depends_on:
      - user-service
    networks:
      - clinic-network
    volumes:
    - ./booking-service/logs:/app/logs


  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "3003:3000"
    networks:
      - clinic-network
    volumes:
    - ./product-service/logs:/app/logs


  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3004:3004"
    networks:
      - clinic-network
    volumes:
    - ./notification-service/logs:/app/logs


networks:
  clinic-network:
